GET http://localhost:8080/api/hello
Accept: application/json

###
POST http://localhost:8080/api/hello
Accept: application/json
Content-Type: application/json

{}

###
GET http://localhost:8080/api/hello/all
Accept: application/json

###
GET http://localhost:8080/api/hello/all?less=2022-01-01
Accept: application/json

###