version: '3'

services:
  travel-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: travel
      MARIADB_USER: traveluser
      MARIADB_PASSWORD: travelpass
      MARIADB_ROOT_PASSWORD: travelroot

  travel-app:
    image: travel-app
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - travel-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://travel-mariadb/travel?useUnicode=true'
    #entrypoint: ['./wait-for-it.sh', '-t', '120', 'hello-mariadb:3306', '--', 'java', 'org.springframework.boot.loader.JarLauncher']
    entrypoint: ['java', 'org.springframework.boot.loader.JarLauncher']